item {
    id: 1
    name: "a_nurses_calling"
}

item {
    id: 2
    name: "ace_in_the_hole"
}

item {
    id: 3
    name: "adrenaline"
}

item {
    id: 4
    name: "aftercare"
}

item {
    id: 5
    name: "agitation"
}

item {
    id: 6
    name: "alert"
}

item {
    id: 7
    name: "any_means_necessary"
}

item {
    id: 8
    name: "appraisal"
}

item {
    id: 9
    name: "autodidact"
}

item {
    id: 10
    name: "balanced_landing"
}

item {
    id: 11
    name: "bamboozle"
}

item {
    id: 12
    name: "bbq_and_chilli"
}

item {
    id: 13
    name: "beast_of_prey"
}

item {
    id: 14
    name: "bite_the_bullet"
}

item {
    id: 15
    name: "bitter_murmur"
}

item {
    id: 16
    name: "blank_perk"
}

item {
    id: 17
    name: "blast_mine"
}

item {
    id: 18
    name: "blood_echo"
}

item {
    id: 19
    name: "blood_pact"
}

item {
    id: 20
    name: "blood_warden"
}

item {
    id: 21
    name: "bloodhound"
}

item {
    id: 22
    name: "boil_over"
}

item {
    id: 23
    name: "bond"
}

item {
    id: 24
    name: "boon:exponential"
}

item {
    id: 25
    name: "boon:shadow_step"
}

item {
    id: 26
    name: "borrowed_time"
}

item {
    id: 27
    name: "botany_knowledge"
}

item {
    id: 28
    name: "breakdown"
}

item {
    id: 29
    name: "breakout"
}

item {
    id: 30
    name: "brutal_strength"
}

item {
    id: 31
    name: "buckle_up"
}

item {
    id: 32
    name: "built_to_last"
}

item {
    id: 33
    name: "calm_spirit"
}

item {
    id: 34
    name: "circle_of_healing"
}

item {
    id: 35
    name: "clairvoyance"
}

item {
    id: 36
    name: "claustrophobia"
}

item {
    id: 37
    name: "corrective_action"
}

item {
    id: 38
    name: "corrupt_intervention"
}

item {
    id: 39
    name: "coulrophobia"
}

item {
    id: 40
    name: "counterforce"
}

item {
    id: 41
    name: "coup_de_grace"
}

item {
    id: 42
    name: "dance_with_me"
}

item {
    id: 43
    name: "dark_devotion"
}

item {
    id: 44
    name: "dark_sense"
}

item {
    id: 45
    name: "dead_hard"
}

item {
    id: 46
    name: "dead_man_switch"
}

item {
    id: 47
    name: "deathbound"
}

item {
    id: 48
    name: "deception"
}

item {
    id: 49
    name: "decisive_strike"
}

item {
    id: 50
    name: "deerstalker"
}

item {
    id: 51
    name: "deja_vu"
}

item {
    id: 52
    name: "deliverance"
}

item {
    id: 53
    name: "desperate_measures"
}

item {
    id: 54
    name: "detectives_hunch"
}

item {
    id: 55
    name: "discordance"
}

item {
    id: 56
    name: "distortion"
}

item {
    id: 57
    name: "distressing"
}

item {
    id: 58
    name: "diversion"
}

item {
    id: 59
    name: "dragons_grip"
}

item {
    id: 60
    name: "dying_light"
}

item {
    id: 61
    name: "empathy"
}

item {
    id: 62
    name: "enduring"
}

item {
    id: 63
    name: "eruption"
}

item {
    id: 64
    name: "fast_track"
}

item {
    id: 65
    name: "fearmonger"
}

item {
    id: 66
    name: "fire_up"
}

item {
    id: 67
    name: "flashbang"
}

item {
    id: 68
    name: "flip_flop"
}

item {
    id: 69
    name: "for_the_people"
}

item {
    id: 70
    name: "forced_penance"
}

item {
    id: 71
    name: "franklins_demise"
}

item {
    id: 72
    name: "furtive_chase"
}

item {
    id: 73
    name: "gearhead"
}

item {
    id: 74
    name: "grim_embrace"
}

item {
    id: 75
    name: "guardian"
}

item {
    id: 76
    name: "hangmans_trick"
}

item {
    id: 77
    name: "head_on"
}

item {
    id: 78
    name: "hex:blood_favor"
}

item {
    id: 79
    name: "hex:crowd_control"
}

item {
    id: 80
    name: "hex:devour_hope"
}

item {
    id: 81
    name: "hex:haunted_grounds"
}

item {
    id: 82
    name: "hex:huntress_lullaby"
}

item {
    id: 83
    name: "hex:pentimento"
}

item {
    id: 84
    name: "hex:retribution"
}

item {
    id: 85
    name: "hex:ruin"
}

item {
    id: 86
    name: "hex:third_seal"
}

item {
    id: 87
    name: "hex:thrill_of_the_hunt"
}

item {
    id: 88
    name: "hex:undying"
}

item {
    id: 89
    name: "hoarder"
}

item {
    id: 90
    name: "hope"
}

item {
    id: 91
    name: "hysteria"
}

item {
    id: 92
    name: "im_all_ears"
}

item {
    id: 93
    name: "infectious_fright"
}

item {
    id: 94
    name: "inner_healing"
}

item {
    id: 95
    name: "insidious"
}

item {
    id: 96
    name: "iron_grasp"
}

item {
    id: 97
    name: "iron_maiden"
}

item {
    id: 98
    name: "iron_will"
}

item {
    id: 99
    name: "jolt"
}

item {
    id: 100
    name: "kindred"
}

item {
    id: 101
    name: "kinship"
}

item {
    id: 102
    name: "knockout"
}

item {
    id: 103
    name: "leader"
}

item {
    id: 104
    name: "left_behind"
}

item {
    id: 105
    name: "lethal_pursuer"
}

item {
    id: 106
    name: "lightborn"
}

item {
    id: 107
    name: "lightweight"
}

item {
    id: 108
    name: "lithe"
}

item {
    id: 109
    name: "lucky_break"
}

item {
    id: 110
    name: "mad_grit"
}

item {
    id: 111
    name: "make_your_choice"
}

item {
    id: 112
    name: "mettle_of_man"
}

item {
    id: 113
    name: "monitor_and_abuse"
}

item {
    id: 114
    name: "monstrous_shrine"
}

item {
    id: 115
    name: "nemesis"
}

item {
    id: 116
    name: "no_mither"
}

item {
    id: 117
    name: "no_one_escapes_death"
}

item {
    id: 118
    name: "no_one_left_behind"
}

item {
    id: 119
    name: "no_way_out"
}

item {
    id: 120
    name: "object_of_obsession"
}

item {
    id: 121
    name: "off_the_record"
}

item {
    id: 122
    name: "open_handed"
}

item {
    id: 123
    name: "oppression"
}

item {
    id: 124
    name: "overcharge"
}

item {
    id: 125
    name: "overcome"
}

item {
    id: 126
    name: "overwhelming_presence"
}

item {
    id: 127
    name: "pain_resonance"
}

item {
    id: 128
    name: "pharmacy"
}

item {
    id: 129
    name: "play_with_your_food"
}

item {
    id: 130
    name: "plunderers_instinct"
}

item {
    id: 131
    name: "poised"
}

item {
    id: 132
    name: "pop_goes_the_weasel"
}

item {
    id: 133
    name: "power_struggle"
}

item {
    id: 134
    name: "predator"
}

item {
    id: 135
    name: "premonition"
}

item {
    id: 136
    name: "prove_thyself"
}

item {
    id: 137
    name: "quick_and_quiet"
}

item {
    id: 138
    name: "rancor"
}

item {
    id: 139
    name: "red_herring"
}

item {
    id: 140
    name: "remember_me"
}

item {
    id: 141
    name: "renewal"
}

item {
    id: 142
    name: "repressed_alliance"
}

item {
    id: 143
    name: "resilience"
}

item {
    id: 144
    name: "resurgence"
}

item {
    id: 145
    name: "rookie_spirit"
}

item {
    id: 146
    name: "saboteur"
}

item {
    id: 147
    name: "save_the_best_for_last"
}

item {
    id: 148
    name: "scourage_hook:pain_resonance"
}

item {
    id: 149
    name: "self_aware"
}

item {
    id: 150
    name: "self_care"
}

item {
    id: 151
    name: "self_healing"
}

item {
    id: 152
    name: "self_preservation"
}

item {
    id: 153
    name: "shadowborn"
}

item {
    id: 154
    name: "situational_awareness"
}

item {
    id: 155
    name: "slippery_meat"
}

item {
    id: 156
    name: "sloppy_butcher"
}

item {
    id: 157
    name: "small_game"
}

item {
    id: 158
    name: "smash_hit"
}

item {
    id: 159
    name: "sole_survivor"
}

item {
    id: 160
    name: "solidarity"
}

item {
    id: 161
    name: "soul_guard"
}

item {
    id: 162
    name: "spies_from_the_shadow"
}

item {
    id: 163
    name: "spine_chill"
}

item {
    id: 164
    name: "spirit_fury"
}

item {
    id: 165
    name: "sprint_burst"
}

item {
    id: 166
    name: "stake_out"
}

item {
    id: 167
    name: "starstruck"
}

item {
    id: 168
    name: "streetwise"
}

item {
    id: 169
    name: "stridor"
}

item {
    id: 170
    name: "surveillance"
}

item {
    id: 171
    name: "technician"
}

item {
    id: 172
    name: "tenacity"
}

item {
    id: 173
    name: "territorial_imperative"
}

item {
    id: 174
    name: "thanatophobia"
}

item {
    id: 175
    name: "this_is_not_happening"
}

item {
    id: 176
    name: "thrilling_tremors"
}

item {
    id: 177
    name: "tinkerer"
}

item {
    id: 178
    name: "trail_of_torment"
}

item {
    id: 179
    name: "unbreakable"
}

item {
    id: 180
    name: "unnerving_presence"
}

item {
    id: 181
    name: "unrelenting"
}

item {
    id: 182
    name: "up_the_ante"
}

item {
    id: 183
    name: "urban_evasion"
}

item {
    id: 184
    name: "vigil"
}

item {
    id: 185
    name: "visionary"
}

item {
    id: 186
    name: "wake_up"
}

item {
    id: 187
    name: "well_make_it"
}

item {
    id: 188
    name: "were_gonna_live_forever"
}

item {
    id: 189
    name: "whispers"
}

item {
    id: 190
    name: "windows_of_opportunity"
}

item {
    id: 191
    name: "zanshin_tactics"
}